
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agentic-ai-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: agentic-ai
  template:
    metadata:
      labels:
        app: agentic-ai
    spec:
      containers:
      - name: agentic-ai
        image: yourregistry.azurecr.io/agentic-ai:latest
        ports:
        - containerPort: 8501
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-secrets
              key: api_key
---
apiVersion: v1
kind: Service
metadata:
  name: agentic-ai-service
spec:
  selector:
    app: agentic-ai
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: LoadBalancer
