name: grc-agentic-ai
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - pip:
    - openai
    - python-dotenv
    - requests
    - beautifulsoup4
    - langchain
    - tiktoken 