name: Monitor App Health

on:
  schedule:
    - cron: '*/30 * * * *'  # Run every 30 minutes
  workflow_dispatch:  # Allow manual trigger

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Check app health
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" https://cybergrc-agent.streamlit.app/)
          if [ "$response" != "200" ]; then
            echo "App is not responding correctly. Status code: $response"
            exit 1
          fi 