name: Monitor App Health

on:
  schedule:
    - cron: '0 */12 * * *'  # Run every 12 hours
  workflow_dispatch:  # Allow manual trigger

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Check app health
        env:
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" https://cybergrc-agent.streamlit.app/)
          if [ "$response" != "200" ]; then
            echo "App is not responding correctly. Status code: $response"
            # Send email using curl to Gmail SMTP
            curl -s --url 'smtp://smtp.gmail.com:587' \
              --mail-from 'skidad75@gmail.com' \
              --mail-rcpt 'skidad75@gmail.com' \
              --ssl-reqd \
              --user 'skidad75@gmail.com:${{ secrets.EMAIL_PASSWORD }}' \
              --upload-file <(echo -e "Subject: 🚨 App Health Check Failed\n\nThe app is not responding correctly. Status code: $response\nTime: $(date)")
            exit 1
          fi 