[openai]
api_key = "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"

[email]
password = "wotu eifm wzwn rzrq"

[monitoring]
enabled = true
check_interval = 30  # minutes 